# Generated by Django 4.1.1 on 2022-10-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('CheckIn', models.DateField(max_length=30)),
                ('CheckOut', models.DateField(max_length=20)),
                ('valorHospedagem', models.FloatField(max_length=30)),
                ('companhia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('horario', models.CharField(max_length=20)),
                ('valorIda', models.FloatField(max_length=30)),
                ('valorVolta', models.FloatField(max_length=20)),
                ('companhia', models.CharField(max_length=30)),
            ],
        ),
    ]
